### ISSUE TITLE
Feedback deleting terms with children

### ISSUE THREAD

**Issue by leogermani** [tainacan/tainacan#153]

**Comment by mateuswetah** [comment]
The solution is simple but not ideal... We can ask for a list reloading at the parents level. The problem is that this causes  any collapse at down to that level to close (and in the future, once we have a checkbox list, it get's even more complicated. So I'm committing this change but with a feeling that we still have challenges to this terms list. Separating the logic of how things are as data and as a view component are really the issue here.
