### ISSUE TITLE
Filter by Status (private vs public)

### ISSUE THREAD

**Issue by mateuswetah** [tainacan/tainacan#248]
Maybe this should be on the tabs, but we need a way to filter items by public or private on the items list.

**Comment by mateuswetah** [comment]
After discussion, we agreed on using existing tabs to deal with this, as long as we keep the "All items" tab to allow easier manipulation of all public and private items. We might discuss design changes tomorrow.

**Comment by leogermani** [comment]
I checked and this is working nicely.

I also checking logging in with a user that do not have permission to see private items and it works as expected.

But, in those cases, I think it would just be better if we hide this tabs, because thay make no sense if the user cant see private items.

There is a user capability called `read_private_tnc_col_{collection_id}_items` for this

**Comment by leogermani** [comment]
Dont you think we could also hide the "Published" tab? since it shows the same results of "all published items"

**Comment by mateuswetah** [comment]
I was thinking about this... but in the future, isn't it possible that other status will fit into that tab that doesn't passes any status value? Because this implies putting a logic of not showing published items when the limitation is actually not having capability for seeing public ones... likes changing the UI and API duality..
