### ISSUE TITLE
Define default metadata to be used to order items list

### ISSUE THREAD

**Issue by leogermani** [tainacan/tainacan#26]

**Comment by mateuswetah** [comment]
How are we on this matter, @leogermani?

**Comment by leogermani** [comment]
It is still an open issue :)

I think we can get it out from the freezer and discuss it. Im not really sure if it would be a good idea to set the default orderby to a metadata and force the user to see the warning that there may be missing items the first time it enters the collection. 

Maybe because we did not solve the issue of keeping all items when ordering by custom metadata, we should not give this option.

For the record, this issue is related to #25

**Comment by mateuswetah** [comment]
I'm curious if we have finished this task or not. Currently the user can define the default sorting metadatum. However, it still has (and possibly will always need) that warning indicating that if the metadatum is a custom one, not all items shall be present, since the query won't bring items that do not contain value for that metadata.

One possible solution for that is using a secondary metadatum for sorting items without value. But there is a separate issue for that: #337 

@vnmedeiros do you agree on closing this?

**Comment by mateuswetah** [comment]
As stated above, this is already implemented. Another discussion is how to handle order by custom post meta when the value does not exists. Currently we are displaying a warning in the UI.
