### ISSUE TITLE
Set the box position of the metadata types as fixed.

### ISSUE THREAD

**Issue by vnmedeiros** [tainacan/tainacan#264]
when defining a large amount of metadata, for example in a collection, the list of metadata types was positioned on top of the screen forcing the user to use the scroll bar to add a new metadata.

**Ideal solution**

make the position of the box of metadata types fixed idepetende of the scroll

**Comment by mateuswetah** [comment]
Implemented. Instead of using a fixed position, I decided to use a fixed height with scroll auto on both columns. This way, when the available metadata column is big enough to create a scroll, we can have both changing side by side instead of a big scroll on page. This made possible to use the same strategy on filters page.

**Comment by leogermani** [comment]
Really 2 scrolls on the page?

![Captura de tela de 2019-06-24 04-59-55](https://user-images.githubusercontent.com/971483/60001556-128e5500-963d-11e9-80f1-7c7464932f08.png)

Maybe just scroll to the end of the page when adding a new metadata?

**Comment by leogermani** [comment]
Another annoying screenshot:

![Captura de tela de 2019-06-24 05-30-52](https://user-images.githubusercontent.com/971483/60004930-ee824200-9643-11e9-98f0-0e1b228244b2.png)

**Comment by mateuswetah** [comment]
Yes, two scrolls rsrs. Because we don't have a control on how both sides will grow. But the effect you are having is really not the expected. The scrolls should happen only in the columns itself, not on the page. So I did some tests and could get rid of the first case (the page-level scroll really shouldn't be there), I'll commit soon. But the empty case, well, this (I need to test here...)
