### ISSUE TITLE
Add support for translating the plugin

### ISSUE THREAD

**Issue by cutterkom** [tainacan/tainacan#426]
I think about adding a translated version of the Tainacan plugin. As common in Wordpress, I expected a `languages` folder with `.po` and `.mo` files in it, but there isn't one.

It seems to me that the translations are added to Tainacan Interface (https://github.com/tainacan/tainacan-theme/blob/develop/src/languages/pt_BR.po), but not the plugin. Nevertheless there had been some kind of translation option as this commit suggets: https://github.com/tainacan/tainacan/pull/48

Is it possible to add support of translating the plugin via `.po`/`.mo` files?

**Comment by leogermani** [comment]
Hi! Thanks for your interest in contributing.

The translation is done in WordPress' collaborative platform at https://translate.wordpress.org/projects/wp-plugins/tainacan/

You can translate it online and it will be available automatically.

Which language do you want to translate it into?

Translations there must be approved by the local community (and not necessarily the plugin owner), so at some point you might need to contact them to get the guidelines for translations. It's usually an easy process, they just want to assure you follow the same standards.

Ayway, if you don't want to go through all this process, you can download the .po from there and translate it. But it would be awesome to have it published there!

**Comment by mateuswetah** [comment]
Hi @cutterkom! 

We use the [WordPress.org translation platform](https://translate.wordpress.org/projects/wp-plugins/tainacan/) for that (for the plugin, the theme still uses `.po` files as you mentioned). 

Previously we kept both schemes, but one of the core developers told me that this could result in issues with the presence of the strings on the hosted version. So if you want to translate the plugin to your language (we would be thrilled with that) you can do it from there. One thing that I know is that you will firstly be submitting strings as `for revision`, because only [allowed translators](https://make.wordpress.org/polyglots/teams/) for each language can approve official translations. I can give you a help asking to to your language to team to add you as an editor. It usually boils down to you getting in touch with them in the WordPress slack.

**Comment by cutterkom** [comment]
Great, I didn't know about that platform. 

If we decide to use Tainacan in a project, I am going to translate it to German.

**Comment by mateuswetah** [comment]
_Danke dir!_

We'll be closing this for now then :)

**Comment by leogermani** [comment]
@cutterkom nice!

Please let us know if you need any assistance or just want to ask questions, understand something in details... we are here to help
