### ISSUE TITLE
Filter bar when using shortcode

### ISSUE THREAD

**Issue by lwdias** [tainacan/tainacan#439]
When using Tainacan in other theme, we need to use the shortcode. However, the shortcode only loads the filter bar on the main page, where all collections are listed, when you click on one of the collections, the filter bar disappears.

It would be great if the filter bar remains in all the pages, just like in the tainacan theme

**Comment by mateuswetah** [comment]
Hi @lwdias,

That does seems a bit weird, but I'm not sure if I understood exactly the problem. The `shortcode` renders a [list of _items_](https://tainacan.github.io/tainacan-wiki/#/tainacan-pages), either from the whole _repository,_ a _term_ or a _collection_. In the Tainacan Interface theme, the term and repository items list contain a collections filter, which you can click to narrow the results... Could you provide us some screenshots to see more clearly where are you referring to?

- BTW, keep in mind that you can use **_Tainacan Faceted Search_** gutenberg block (so far this page is only in Portuguese, sorry): https://tainacan.github.io/tainacan-wiki/#/pt-br/blocks-items?id=busca-facetada;
- And that if you've got your hands dirty with templates code, it is probably better to implement the support to your theme to items list, instead of using the shorcode. That should't require much work, really: https://tainacan.github.io/tainacan-wiki/#/dev/creating-compatible-themes. If you need any support on this I am at your disposal;

**Comment by mateuswetah** [comment]
Hi @lwdias, did you have any results on this?

**Comment by nodo-dev** [comment]
Hi! Thank you for your help! I tried again with the shortcode and now it worked, i don't know what happened before.
Thank you so much!

**Comment by lwdias** [comment]
Hi! Thank you for your help! I tried again with the shortcode and now it worked, i don't know what happened before.
Thank you so much!
