### ISSUE TITLE
Offer responsive/retina images

### ISSUE THREAD

**Issue by Ambrosiani** [tainacan/tainacan#467]
**Context and motivation**

Images are blurry on retina screens.

**Ideal solution**

I guess using srcset is the modern solution?

**Alternative solutions**

Maybe support plugins like [Perfect Images + Retina?](https://wordpress.org/plugins/wp-retina-2x/) – they require themes to use img tags instead of background-image for instance.

**Additional context**

Example of blurry images: https://monument.kvinnohistoriska.se/kvinnans-sak/?view_mode=masonry&perpage=12&paged=1&order=ASC&orderby=date&fetch_only=thumbnail%2Ccreation_date%2Ctitle%2Cdescription&fetch_only_meta=

**Comment by Ambrosiani** [comment]
also – if I want to manually change thumbnail sizes, for instance here, https://github.com/tainacan/tainacan/blob/891ae5ea17ada48bffc597c4315ab0bf47f0c30c/src/views/gutenberg-blocks/tainacan-items/items-list/items-modal.js#L98, from "tainacan-medium" to "large", how do I get that into the production code?

**Comment by mateuswetah** [comment]
Hi @Ambrosiani.

Unfortunately, we don't have a current implementation of image responsiveness with `srcset` options. That is surely an important demand and I believe we might take a look at it as we have some issues opened that relate to items thumbnail (#463, #319 and #456).

Allowing customization of image crop sizes is a challenging task as we have items displayed in a variety of sizes all across the plugin interface.

Regarding using `imgs` tags instead of `background-image`, you are lucky there because even though Masonry items use it, they still have the original `img`. That is done to enable the "loading skeleton" effect that we intent to replace on #463. If you want you can test it by using the following css:

```css
.tainacan-masonry-container .tainacan-masonry-item .tainacan-masonry-item-thumbnail img:not(.skeleton) {
    visibility: visible !important;
}
.tainacan-masonry-container .tainacan-masonry-item .tainacan-masonry-item-thumbnail {
    background: none !important;
}
```

If you are interested on changing this in the plugin code, what you are looking for is probably this line:
https://github.com/tainacan/tainacan/blob/891ae5ea17ada48bffc597c4315ab0bf47f0c30c/src/views/theme-search/components/view-mode-masonry.vue#L76

But building the plugin for production ready requires you to have a build environment ready. We have instructions for that here:
https://tainacan.github.io/tainacan-wiki/#/dev/setup-local

And we also have a Docker image, in case you prefer this for a local development: https://github.com/tainacan/tainacan-docker

If you are not able to build it and this is a strong, immediate necessity, I can make you a custom build and send you the `.zip`

In any case we'll look into the `srcset` solution and discuss a better way to offer tweaking this settings. 

For now, although it won't solve your issue I would also suggest you to try on the "Tainacan Collection's Items List" gutenberg block. As you are offering an items list with so few controls, it might provide you better display options.

**Comment by Ambrosiani** [comment]
@mateuswetah thank you! I'll look into the dev setup to begin with. #463 sounds like a great addition – will probably look to implement that on our websites too 😃
