### ISSUE TITLE
Add link/metadata from created entry to form submission feedback

### ISSUE THREAD

**Issue by Ambrosiani** [tainacan/tainacan#468]
**Context and motivation**

Thank you for implementing the submission form #388! One really good improvement would be the possibility to include metadata and/or other information from the created entry directly into the submission feedback. That way, the contributor could directly view their uploaded entry (and share it on social media etc) without having to follow

<img width="274" alt="Skärmavbild 2020-12-21 kl  14 24 32" src="https://user-images.githubusercontent.com/2394405/102781698-672ca080-4398-11eb-9a0b-84ebf272bb96.png">

**Ideal solution**

Perhaps a toggle "display permalink in submission feedback", or a shortcode that can be used in the current textbox?

**Comment by mateuswetah** [comment]
That's a great ideia actually. We would only have to check if the submission was set to be directly published as "publish" instead of "draft" or "private" because some collection administrator might prefer to have the submission on a review process. In any case, I'll add it to our wish list for the next big release :)
