### ISSUE TITLE
Can't Install via Wordpress

### ISSUE THREAD

**Issue by joshcastellano** [tainacan/tainacan#829]
**Bug description**

As of yesterday 11/17/2023 the Wordpress repository for installing plugins has closed downloads to Tainacan. Therefore can't Tainacan cannot be installed via normal means.

**How to reproduce such bug**

Got to the Wordpress plugin module or go to the Wordpress Plugin website and see for yourself.
https://wordpress.org/plugins/tainacan/

**Screenshots**
<img width="977" alt="Screen Shot 2023-11-18 at 8 05 05 AM" src="https://github.com/tainacan/tainacan/assets/35434544/bc1d378c-99e2-4801-91ee-8bd891345bd6">

**Suggestion**
Package this here on github ready for install.

**Comment by mateuswetah** [comment]
Hi @joshcastellano!

Sadly, yesterday our WordPress link was temporally blocked due to a risk of XSS attack identified by a contributor. We already made the necessary commits to solve the issue, but their evaluation if it in fact solves the risk will probably be only ready during next week.

Meanwhile, you can now download the plugin here in our github releases page. I'll see if later today we publish a temporary release that also includes the security patches :)

Thanks for warning and understanding!

**Comment by mateuswetah** [comment]
We're back :)

https://wordpress.org/plugins/tainacan/
