### ISSUE TITLE
Question: integrating Tainacan with an LMS

### ISSUE THREAD

**Issue by dhowe** [tainacan/tainacan#846]
This is a really question rather than a feature request, but can Tainacan integrate with Learning Management plugins like LearnPress or similar ? I'm looking for an OSS solution to a _combined_ digital repository and classroom support platform for a large international arts institution. Tainacan looks great, but I was hoping to verify, at least provisionally, that it would play nice with an LMS -- if anyone had experience with this, would be fantastic... thanks!

**Comment by mateuswetah** [comment]
Hi @dhowe!

To put it simply, there is no official integration with LearnPress. I can imagine, however, that something can be built, since Tainacan collections and items are, behind the scenes, WordPress Custom Post Types. So it might be possible to imagine templates where you present information of a course, lets say, and a list of items from a collection. In any case, this or more complex features would probably require putting hands on code. If you are or happen to know developers who want to investigate this path we can provide support for sure. 

I'm closing this issue, but feel free to move any discussion on in our forum, it is a better place for this kind of question since more people may be interested: https://tainacan.discourse.group/

**Comment by dhowe** [comment]
thanks @mateuswetah I will follow-up on the discourse 
one questions: what types of support, if any, do you offer for institutions using tainacan ?

**Comment by mateuswetah** [comment]
> what types of support, if any, do you offer for institutions using tainacan

In the previous message I meant helping other developers to understand our documentation, hooks, and internals so they can implement such integration

More broadly, Tainacan development is maintained by institutions which can pay for custom development of features and sometimes support, while we do not have a centralized company that could answer for/in the name of the plugin. Currently, we've been working hard towards some features desired by the Brazilian Institute of Museums (IBRAM). Free guidance and orientation is always provided in our own pace via Discourse forum. But for more dedicated support, usually we would recommend someone or chat to see if we can find a suitable work in our team members.

**Comment by dhowe** [comment]
great, thanks
