### ISSUE TITLE
CSV Importer: Add support for datetime field

### ISSUE THREAD

**Issue by alantygel** [tainacan/tainacan#899]
**Context and motivation**

Currently, on import CSV feature, if a column is marked as `date`, only the format YYYY-MM-DD is accepted. However, when importing a database from another system, it is possible that one may want to import datetime fields in format YYYY-MM-DD HH:MM:SS.

**Ideal solution**

Include a `datetime` flag for importing datetime fields;

**Alternative solutions**

Another option, is to detect datetime fields when using `Date` flag.

**Comment by mateuswetah** [comment]
Currently our date metadata only accepts year, month and day. Changing this would be hard because our date is really stored only as a date string (yyyy-mm-dd), not the full timestamp encoding. A future implementation of this would probably create another type of metadata, one that accepts full timestamp.

While I see a path for this, I don't believe it would be early in our priorities, because it is not a scenario that seems common for most of our known use cases. At least not in a way that a separate numeric metadata for time wouldn't be enough...

**Comment by mateuswetah** [comment]
However, if you are willing to contribute, we have some documentation regarding creating new metadata types. We could help you follow that path in a plugin if you consider it to be essential for your project and maybe it could even became part of the core, after some validation:
https://tainacan.github.io/tainacan-wiki/#/dev/creating-metadata-type

**Comment by mateuswetah** [comment]
After some discussion, we consider that having a Timestamp metadata type is something relevant that should be in our future roadmap. For that we opened a new issue:
#920 

Which should also include expectations for the importer field. 

Would you agree on closing this issue in favor of that? I can still see some relevance on adding an option to the importer where it could just ignore the `HH:MM:SS` part of the field to store date only values, but for me that seems like a work that could be easily manipulated in spreadsheeds when preparing the CSV for the importer.
